### PR TITLE
feat: Add new API to deploy to cloudflare pages to get network version info

### PR DESCRIPTION
**Pull request by rdoria1**

### CODE REVIEW

**Review by otoumas — APPROVED** [review]
LGTM

**Review by lander86 — APPROVED** [review]
LGTM

**Comment by ysibirski** [comment]
@rdoria1 looks good to me, but could you please explain me how it works :) How are we going to be keeping track of evmapp versions and update .json file or we do not need to worry about it?

Thank you in advance

**Comment by rdoria1** [comment]
> @rdoria1 looks good to me, but could you please explain me how it works :) How are we going to be keeping track of evmapp versions and update .json file or we do not need to worry about it?
> 
> Thank you in advance

@ysibirski 
Sure thing! So after a discussion with @lander86, we actually want to do this manually for now because automatizing at this point isn't really possible/ideal (if a new version comes out, we don't necessarily want it to be the official new release that partners will fetch from that endpoint) eventually when the workflow is clear we will want to automatize it.

**Comment by paolocappelletti** [comment]
hi guys next time please always open a pr against development branch first
A merge to master should be performed only when a new release is created, and coordinated with myself and @lander86

**Pull request merged**
