### PR TITLE
CICD to build evmapp image and push it

### PR DESCRIPTION
**Pull request by ysibirski**
This PR introduces CICD for building docker image of EON app. There are couple of things I would like to ask @paolocappelletti if we can do a bit diff on this repo to match with our other releases repos like SDK, cryptolib, sparkz and etc.

1) Can we build PROD versions ONLY off `main` branch and it has to be in the format of `digit.digit.digit`
2) Can we build DEV versions ONLY off `development` branch and it has to be in the format of `digit.digit.digit-SNAPSHOT` Keep it in mind SNAPSHOT without any digits after. However, GITHUB TAG can be named `digit.digit.digit-SNAPSHOT[0-9]*` if needed. By doing this we will ensure new code is being released but version of the PACKAGE stays the same from within APP level.

I will be happy to hear some comments, concerns regarding this. 

P.S. We will be adding `mvn` build and test commands to the pipeline in the nearest future as well.

### CODE REVIEW

**Review by lander86 — APPROVED** [review]
I agree with 1. and 2. ; that's essentially what we are already doing on other repositories. 
@paolocappelletti at the moment we're just implementing the build (and push) of the docker image and essentially nothing else because it's what we needed but, as mentioned by Yuri, let's discuss what we should or would like to add.

**Review by otoumas — APPROVED** [review]
LGTM

**Comment by paolocappelletti** [comment]
going to approve and merge! 
no problems on the tag conventions!  I just followed previous style by Oleksander but  agree is better to unify it.

**Review by paolocappelletti — APPROVED** [review]

**Comment by ysibirski** [comment]
@paolocappelletti I am going to add YOUR GPG key to MAINTAINERS_KEYS, thus you will the only ONE + infra be able to build a RELEASE version that will be pushed to Docker Repos. It means YOU the one who needs to create a TAG off main or dev branch and push it to ORIGIN.

Could you please give you me PUBLIC GPG key as well as upload it to ONE of the following key servers(if not already uploaded):

```
https://keys.openpgp.org/ 
https://keyserver.ubuntu.com/
https://pgp.mit.edu/
```

**Pull request merged**
